# Generated by Django 4.2.6 on 2023-10-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanual',
            name='filepath',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
