# Generated by Django 4.2.7 on 2023-11-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manual', '0002_usermanual_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanual',
            name='sub_category_1',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanual',
            name='sub_category_2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
