# Generated by Django 4.2.6 on 2023-12-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manual', '0003_usermanual_sub_category_1_usermanual_sub_category_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('cat_1', models.CharField(max_length=100)),
                ('cat_2', models.CharField(max_length=100)),
            ],
        ),
    ]
