# Generated by Django 4.2.6 on 2023-12-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manual', '0004_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='First_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manual.filetype')),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='user_manual.first_category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='user_manual.filetype')),
            ],
        ),
    ]
